# Check if a user-input graph is a tree.

---

## Graph

A set of finite vertices and a set of finite edges connecting the vertices

#### Connected Graph:
A graph in which there is a path joining each pair of vertices, the graph being undirected. It is always possible to travel in a connected graph between one vertex and any other; no vertex is isolated. If a graph is not connected it will consist of several components, each of which is connected; such a graph is said to be disconnected.

#### Cyclic Graph:
A cycle in a graph is a non-empty trail in which the only repeated vertices are the first and last vertices. A directed cycle in a directed graph is a non-empty directed trail in which the only repeated are the first and last vertices.

A graph without cycles is called an acyclic graph. A directed graph without directed cycles is called a directed acyclic graph. A connected graph without cycles is called a tree.

#### Directed Graph:
Edges have a direction from one vertex to another

---

## Tree

A connected, acyclic, undirected graph is a tree

In [4]:
import numpy

In [38]:
# Check if graph is directed or not
# undirected graph -> transpose of adjacency matrix is same as adjacency matrix


# USER INPUT -> ADJACENCY MATRIX


V = int(input("Enter the number of vertices:")) 

am = []   # adjacency matrix
print("Enter the elements of the adjacency matrix row-wise:") 
for i in range(V):          # loop for row entries 
    temp = [] 
    for j in range(V):      # loop for column entries 
         temp.append(int(input())) 
    am.append(temp)

print("Adjacency matrix:")
for row in am:
    print(row)
print()


# DIRECTED OR NOT


def isDirected(a):
    t = numpy.transpose(a)   # transpose of matrix
    if areSame(a, t)==1:
        return 1   # undirected (matrix = transpose)
    elif areSame(a, t)==0:
        return 0   # directed (matrix != transpose)
    
def areSame(a, b):
    for i in range(V): 
        for j in range(V): 
            if (a[i][j] != b[i][j]): 
                return 0   # transpose != matrix
    return 1   # transpose == matrix

if isDirected(am)==1:
    print("Undirected Graph")
else:
    print("Directed Graph")

Enter the number of vertices:3
Enter the elements of the adjacency matrix row-wise:
0
1
1
1
0
1
1
1
0
Adjacency matrix:
[0, 1, 1]
[1, 0, 1]
[1, 1, 0]

Undirected Graph


In [2]:
# Check if graph is cyclic or acyclic
# use bfs/dfs



In [3]:
# Check if graph is connected
# bfs/dfs from any vertex and check if all vertices are covered 



In [19]:
# matrix - transpose equality check

V = int(input("Enter the number of vertices:")) 

am = [] 
print("Enter the entries row wise:") 

for i in range(V):          # loop for row entries 
    a = [] 
    for j in range(V):      # loop for column entries 
         a.append(int(input())) 
    am.append(a)

for row in am:
    print(row)
    
tam = numpy.transpose(am)
print(tam)
print()

def areSame(a, b):
    for i in range(V): 
        for j in range(V): 
            if (a[i][j] != b[i][j]): 
                return 0
    return 1

if areSame(am,tam)==1:
    print("Matrix = transpose")
else:
    print("Matrix != transpose")

Enter the number of vertices:3
Enter the entries row wise:
0
1
1
1
0
1
1
1
0
[0, 1, 1]
[1, 0, 1]
[1, 1, 0]
[[0 1 1]
 [1 0 1]
 [1 1 0]]

Matrix = transpose


In [3]:
# User input adjacency matrix

V = int(input("Enter the number of vertices:")) 

am = [] 
print("Enter the entries row wise:") 

for i in range(V):          # loop for row entries 
    a = [] 
    for j in range(V):      # loop for column entries 
         a.append(int(input())) 
    am.append(a)

for row in am:
    print(row)

Enter the number of vertices:3
Enter the entries row wise:
0
1
1
1
0
1
1
1
0
[0, 1, 1]
[1, 0, 1]
[1, 1, 0]


In [12]:
# 2D array representation

rows, cols = (5, 5) 

arr = [[0 for i in range(cols)] for j in range(rows)]
  
for row in arr: 
    print(row) 


[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


In [1]:
# A basic code for matrix input from user 
  
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
  
# Initialize matrix 
matrix = [] 
print("Enter the entries rowwise:") 
  
# For user input 
for i in range(R):          # A for loop for row entries 
    a =[] 
    for j in range(C):      # A for loop for column entries 
         a.append(int(input())) 
    matrix.append(a) 
  
# For printing the matrix 
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print() 

Enter the number of rows:3
Enter the number of columns:2
Enter the entries rowwise:
1
2
3
4
5
6
1 2 
3 4 
5 6 


In [7]:
matrix=[[1,2,3],
            [4,5,6]] 

for row in matrix:
    print(row)

print("\n") 
print(numpy.transpose(matrix)) 

[1, 2, 3]
[4, 5, 6]


[[1 4]
 [2 5]
 [3 6]]
